# This is a github action workflow file that runs tests
# see: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Run Tests

# events that "trigger" this workflow
# see: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [master, main]
  pull_request:
  workflow_dispatch:

# this section cancels any in-progress runs of this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# this section defines the jobs that run in this workflow
# see: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  test:
    name: ${{ matrix.platform }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix: # defines the matrix of platforms and python versions to test
        python-version: ["3.8"]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # checkout the repository
      - uses: actions/checkout@v4
      # install ffmpeg
      - uses: FedericoCarboni/setup-ffmpeg@v3
      # install xvfb and libraries for headless display on windows and linux
      - uses: pyvista/setup-headless-display-action@v2
        with:
          qt: true

      # setup a specific python version
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # cache pip downloads to speed up workflow, invalidate when setup.py changes
          cache: 'pip'
          cache-dependency-path: 'setup.py'

      # Install this package and its dependencies
      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install .[test]

      # Run tests using pytest
      - name: Run Tests
        uses: aganders3/headless-gui@v2
        with:
          run: pytest --color=yes --cov --cov-report=xml --cov-report=term-missing

      # Upload test coverage to codecov
      - name: Coverage
        uses: codecov/codecov-action@v4
